import { AccountInfo } from "stores";

export const registeredAccountData: AccountInfo = [
  {
    id: "1",
    email: "hieptth71@user.com",
    password: "noPassword!23",
    username: "HiepTTH_User",
    role: "user",
    status: 1,
  },
  {
    id: "2",
    email: "hieptth71@agent.com",
    password: "noPassword!23",
    username: "HiepTTH_Agent",
    role: "agent",
    status: 1,
  },
  {
    id: "3",
    email: "user3@example.com",
    password: "password3!23",
    role: "user",
    status: 1,
  },
  {
    id: "4",
    email: "user4@example.com",
    password: "password4!23",
    role: "user",
    status: 1,
  },
  {
    id: "5",
    email: "user5@example.com",
    password: "password5!23",
    role: "user",
    status: 1,
  },
  {
    id: "6",
    email: "user6@example.com",
    password: "password6!23",
    role: "user",
    status: 1,
  },
  {
    id: "7",
    email: "user7@example.com",
    password: "password7!23",
    role: "user",
    status: 1,
  },
  {
    id: "8",
    email: "user8@example.com",
    password: "password8!23",
    role: "user",
    status: 1,
  },
  {
    id: "9",
    email: "user9@example.com",
    password: "password9!23",
    role: "user",
    status: 1,
  },
  {
    id: "10",
    email: "user10@example.com",
    password: "password10!23",
    role: "user",
    status: 1,
  },
  {
    id: "11",
    email: "user11@example.com",
    password: "password11!23",
    role: "user",
    status: 1,
  },
  {
    id: "12",
    email: "user12@example.com",
    password: "password12!23",
    role: "user",
    status: 1,
  },
  {
    id: "13",
    email: "user13@example.com",
    password: "password13!23",
    role: "user",
    status: 1,
  },
  {
    id: "14",
    email: "user14@example.com",
    password: "password14!23",
    role: "user",
    status: 1,
  },
  {
    id: "15",
    email: "user15@example.com",
    password: "password15!23",
    role: "user",
    status: 1,
  },
  {
    id: "16",
    email: "user16@example.com",
    password: "password16!23",
    role: "user",
    status: 1,
  },
];
