export const dummyAppointment = [
  {
    id: 1,
    schedulerName: "Esthera Jackson",
    schedulerEmail: "esthera@simmmple.com",
    propertyAddress: "255 Le Quang Sung Street, HCM City, District 1",
    status: "Accepted",
    inquiredAt: "2024-06-14",
  },
  {
    id: 2,
    schedulerName: "Alexa Liras",
    schedulerEmail: "alexa@simmmple.com",
    propertyAddress: "255 Le Quang Sung Street, HCM City, District 1",
    status: "Rejected",
    inquiredAt: "2024-06-14",
  },
  {
    id: 3,
    schedulerName: "Laurent Michael",
    schedulerEmail: "laurent@simmmple.com",
    propertyAddress: "255 Le Quang Sung Street, HCM City, District 1",
    status: "Pending",
    inquiredAt: "2024-06-14",
  },
  {
    id: 4,
    schedulerName: "Freduardo Hill",
    schedulerEmail: "freduardo@simmmple.com",
    propertyAddress: "255 Le Quang Sung Street, HCM City, District 1",
    status: "Accepted",
    inquiredAt: "2024-06-14",
  },
  {
    id: 5,
    schedulerName: "Daniel Thomas",
    schedulerEmail: "daniel@simmmple.com",
    propertyAddress: "255 Le Quang Sung Street, HCM City, District 1",
    status: "Accepted",
    inquiredAt: "2024-06-14",
  },
  {
    id: 6,
    schedulerName: "Mark Wilson",
    schedulerEmail: "mark@simmmple.com",
    propertyAddress: "255 Le Quang Sung Street, HCM City, District 1",
    status: "Accepted",
    inquiredAt: "2024-06-14",
  },
  {
    id: 7,
    schedulerName: "Jane Doe",
    schedulerEmail: "jane@simmmple.com",
    propertyAddress: "123 Nguyen Trai Street, HCM City, District 1",
    status: "Accepted",
    inquiredAt: "2024-07-14",
  },
  {
    id: 8,
    schedulerName: "John Smith",
    schedulerEmail: "john@simmmple.com",
    propertyAddress: "456 Nguyen Van Cu Street, HCM City, District 5",
    status: "Accepted",
    inquiredAt: "2024-07-15",
  },
  {
    id: 9,
    schedulerName: "Alice Johnson",
    schedulerEmail: "alice@simmmple.com",
    propertyAddress: "789 Le Van Sy Street, HCM City, District 3",
    status: "Accepted",
    inquiredAt: "2024-07-16",
  },
  {
    id: 10,
    schedulerName: "Bob Brown",
    schedulerEmail: "bob@simmmple.com",
    propertyAddress: "101 Le Loi Street, HCM City, District 1",
    status: "Accepted",
    inquiredAt: "2024-07-17",
  },
];
