export const dummyPropertyData = [
  {
    id: "1",
    imageUrl: "https://via.placeholder.com/150",
    title: "Property 1",
    price: "1,000,000",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sqft: "2,500",
    status: "For Sale",
    location: "1234 Elm St, San Diego, CA 92101",
    mapPosition: {
      lat: 32.715736,
      lng: -117.161087,
    },
    amenities: {
      interior: {
        kitchen: "Granite Countertops",
        laundry: "Washer/Dryer",
        fireplace: "Gas",
        appliances: "Stainless Steel",
        flooring: "Hardwood",
        bedrooms: 3,
        bathrooms: 2.5,
      },
      exterior: {
        stories: "2",
        pool: "Inground",
        heat: "Central",
        garage: "2 Car",
        security: "Alarm",
        sewer: "Public",
        other: "Fenced Yard",
        parking: "Driveway",
        lotFeatures: "Corner Lot",
        roof: "Shingle",
      },
      areaLot: {
        lotArea: 0.25,
        livingArea: 2500,
        yearBuilt: 1995,
        viewDescription: "City",
        architecturalStyle: "Contemporary",
        status: "Active",
      },
    },
  },
  {
    id: "2",
    imageUrl: "https://via.placeholder.com/150",
    title: "Property 2",
    price: "1,500,000",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sqft: "3,500",
    status: "For Sale",
    location: "5678 Maple St, San Diego, CA 92101",
    mapPosition: {
      lat: 32.715736,
      lng: -117.161087,
    },
    amenities: {
      interior: {
        kitchen: "Granite Countertops",
        laundry: "Washer/Dryer",
        fireplace: "Gas",
        appliances: "Stainless Steel",
        flooring: "Hardwood",
        bedrooms: 4,
        bathrooms: 3.5,
      },
      exterior: {
        stories: "2",
        pool: "Inground",
        heat: "Central",
        garage: "2 Car",
        security: "Alarm",
        sewer: "Public",
        other: "Fenced Yard",
        parking: "Driveway",
        lotFeatures: "Corner Lot",
        roof: "Shingle",
      },
      areaLot: {
        lotArea: 0.25,
        livingArea: 3500,
        yearBuilt: 1995,
        viewDescription: "City",
        architecturalStyle: "Contemporary",
        status: "Active",
      },
    },
  },
];
